import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'

const supabaseAdmin = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

const resend = new Resend(process.env.RESEND_API_KEY)

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { first_name, last_name, company_name, phone, email } = req.body || {}

  if (!first_name || !last_name || !phone || !email) {
    return res.status(400).json({ error: 'Pflichtfelder fehlen: first_name, last_name, phone, email' })
  }

  // Check if email already submitted
  const { data: existing } = await supabaseAdmin
    .from('brochure_requests')
    .select('id, opt_in_token, email_confirmed_at, access_token')
    .eq('email', email)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  if (existing) {
    if (existing.email_confirmed_at) {
      return res.status(409).json({ error: 'already_confirmed' })
    }

    // Already submitted but not confirmed — resend confirmation email
    const emailError = await sendConfirmationEmail({ first_name, email, opt_in_token: existing.opt_in_token })
    if (emailError) return res.status(500).json({ error: `E-Mail konnte nicht gesendet werden: ${emailError}` })
    return res.json({ success: true, resent: true })
  }

  // Get latest brochure version
  const { data: version } = await supabaseAdmin
    .from('brochure_versions')
    .select('id')
    .order('version_number', { ascending: false })
    .limit(1)
    .single()

  // Insert new request (opt_in_token generated by DB default)
  const { data: request, error: insertError } = await supabaseAdmin
    .from('brochure_requests')
    .insert({
      first_name,
      last_name,
      company_name: company_name || null,
      phone,
      email,
      brochure_version_id: version?.id || null,
    })
    .select('id, opt_in_token')
    .single()

  if (insertError || !request) {
    console.error('brochure/request insert error:', insertError)
    return res.status(500).json({ error: 'Fehler beim Speichern der Anfrage' })
  }

  const emailError = await sendConfirmationEmail({ first_name, email, opt_in_token: request.opt_in_token })
  if (emailError) {
    console.error('brochure/request email error:', emailError)
    return res.status(500).json({ error: `E-Mail konnte nicht gesendet werden: ${emailError}` })
  }

  return res.json({ success: true })
}

// Returns error string on failure, null on success
async function sendConfirmationEmail({ first_name, email, opt_in_token }) {
  const baseUrl = (process.env.FRONTEND_URL || '').replace(/\/$/, '')
  if (!baseUrl) return 'FRONTEND_URL Umgebungsvariable fehlt'
  const confirmUrl = `${baseUrl}/api/brochure/confirm?token=${opt_in_token}`

  const { error } = await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev',
    to: email,
    subject: 'Bitte bestätigen Sie Ihre E-Mail-Adresse – FKVI Broschüre',
    html: `<!DOCTYPE html>
<html lang="de">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f7fa;font-family:'Segoe UI',Arial,sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f7fa;padding:40px 16px">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:580px;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08)">
        <tr>
          <td style="background:#1e3a5f;padding:32px 40px;text-align:center">
            <p style="margin:0;color:#ffffff;font-size:26px;font-weight:700;letter-spacing:-0.5px">FKVI</p>
            <p style="margin:6px 0 0;color:rgba(255,255,255,0.65);font-size:12px;letter-spacing:1px;text-transform:uppercase">Fachkraft Vermittlung International</p>
          </td>
        </tr>
        <tr>
          <td style="padding:40px 40px 32px">
            <h1 style="margin:0 0 8px;font-size:22px;font-weight:700;color:#111827">Fast geschafft, ${first_name}!</h1>
            <p style="margin:0 0 24px;font-size:15px;color:#6b7280">Bitte bestätigen Sie Ihre E-Mail-Adresse, um Zugang zur FKVI-Broschüre zu erhalten.</p>
            <p style="margin:0 0 24px;font-size:15px;color:#374151;line-height:1.6">
              Vielen Dank für Ihr Interesse an unserer Broschüre. Nach der Bestätigung Ihrer E-Mail-Adresse erhalten Sie sofortigen Zugang zum Download.
            </p>
            <table cellpadding="0" cellspacing="0" style="margin:0 0 32px">
              <tr>
                <td style="background:#1e3a5f;border-radius:8px;padding:16px 32px">
                  <a href="${confirmUrl}" style="color:#ffffff;font-size:16px;font-weight:600;text-decoration:none;display:block">
                    E-Mail bestätigen
                  </a>
                </td>
              </tr>
            </table>
            <p style="margin:0 0 8px;font-size:13px;color:#9ca3af">
              Wenn der Button nicht funktioniert, kopieren Sie bitte diesen Link in Ihren Browser:
            </p>
            <p style="margin:0;font-size:12px;color:#6b7280;word-break:break-all">${confirmUrl}</p>
          </td>
        </tr>
        <tr>
          <td style="background:#f9fafb;border-top:1px solid #e5e7eb;padding:24px 40px;text-align:center">
            <p style="margin:0;font-size:13px;color:#9ca3af">
              Falls Sie diese Anfrage nicht gestellt haben, können Sie diese E-Mail ignorieren.<br>
              <strong style="color:#6b7280">Ihr FKVI-Team</strong>
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  })
  return error ? error.message || JSON.stringify(error) : null
}
